### ISSUE TITLE
How to get `to()` and `toEventually()` work with vanilla Swift classes?

### ISSUE THREAD

**Issue by tobinharris** [Quick/Nimble#119]
When running the test, I get the following:

`Cannot invoke 'toEventually' with an argument list of type '(NonNilMatcherFunc<NSObject>)'`

![image](https://cloud.githubusercontent.com/assets/25578/7116250/092bf2fa-e1e8-11e4-8f95-c11a7b932425.png)

My `Authentication` class is just a vanilla Swift class with a couple of properties. Does it need more? I noticed a mention of `NSObject` in the Nimble source, perhaps I need to subclass that for `toEventually` to work? Should nimble work with vanilla Swift classes?

    class AuthenticationTests: XCTestCase {

      var authentication = Authentication()
  
      func testCanPassAuthentication() {
        authentication.authenticate("123456")
        expect(authentication).toEventually(beAnInstanceOf(Authentication))
      }
    }

**Comment by rbeeger** [comment]
That's because Swift is missing the necessary reflection features to find out if a Swift object is a member of a Swift class.

You can use 
```swift
expect(authentication as? Authentication).toNot(beNil())
```
but unless you have some more compilicated class hierarchy XCode will tell you that ```authentication as? Authentication``` is an unnecessary cast.

While you can write such tests in your code you cannot do it on the meta level where the matchers are implemented. So ```beInstanceOf```and ```beAKindOf```only work with ```NSObject```s because you can ask those whether they belong to a class or not.

This is actually not a problem of to() and toEventually() but an issue with the used matchers.

**Comment by jeffh** [comment]
As what @rbeeger says.

It's generally bad form to do assert against a concrete type. Usually it's an indirect validation. A concrete type-check is a proxy assertion: by assuming particular type supports all the behavior you intend.

While it might be possible to do this assertion with Swift types, those matchers would never fail if they compiled since Swift's type checker will ensure that your types always conform. I considered adding it, but deemed it more detrimental to writing good tests than their potential benefit (if any).

(Objective-C types don't ensure type-correctness so it makes more sense.)

**Comment by rbeeger** [comment]
A situation where testing for membership to a class or conformance to a protocol can be useful is when you write a test for a factory that creates instances of different classes based on which parameters it is given.

In that case you know that the factory returns ```MyGenericProduct```, but you want to test that it returns a ```MySpecializedProduct``` if you pass it some specific value as a parameter.

**Comment by tobinharris** [comment]
Hi folks. 

Thanks for the feedback. @rbeeger, the cast worked, along with checking for nil.

    func testCanPassAuthentication() {
      authentication.authenticate("123456")
      expect(self.authentication.state.value as? Authentication.Authenticating).toEventuallyNot(beNil())
      expect(self.authentication.state.value as? Authentication.Passed).toEventuallyNot(beNil())
    }

I think factories are a good case for asserting the correct class is instantiated. Or eventually instantiated in an async situation. In this case, I'm using class to differentiate state changes - just an experiment :)

**Comment by rbeeger** [comment]
@tobinharris I don't know your exact situation here, but using a class for each authentication state looks a bit overly complicated. 

Using an enum seems like a natural fit here. If you need different behaviors in the authentication state you can write methods that switch over the enum itself and even more complicated situations can be implemented with associated values. So if you wanted to know what user name was used for the authentication you could specify it with one. 

Enums are way more powerful in Swift than they ever were in Objective-C.

**Comment by tobinharris** [comment]
Cheers @rbeeger, I'll check out the Swift enums for this. I just got started with Swift.

I'm mainly playing with ideas on how to slim down my controllers and create a testable, simple, lightweight service layer. I'm not sure it's smelling right yet :)

![image](https://cloud.githubusercontent.com/assets/25578/7133724/192f700e-e28e-11e4-8f98-8f0983a0ae7b.png)

**Comment by jeffh** [comment]
@rbeeger, I'd say that concrete types that a factory produces behind a protocol (or parent) type is an implementation detail. The caller should probably never know the concrete types. But I see that testing factories tend to make the sense for brevity's sake.
