### ISSUE TITLE
Cocoapods + Nimble - won't build on device when bitcode generation is enabled

### ISSUE THREAD

**Issue by bielikb** [Quick/Nimble#196]
Simple solution for cocoapods = turn off bitcode generation.

I'm using Nimble outside of XCTest target

`ld: '/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS9.0.sdk/Developer/Library/Frameworks/XCTest.framework/XCTest' does not contain bitcode. You must rebuild it with bitcode enabled (Xcode setting ENABLE_BITCODE), obtain an updated library from the vendor, or disable bitcode for this target. for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)`

**Comment by jeffh** [comment]
Hey @bielikb,

This has been a past issue before. Bitcode generation is disabled on Nimble because XCTest doesn't support it either - which gives errors that you see.

Although since you've mentioned you're not linking to XCTest, have you correctly added the removed script mention in the [README section](https://github.com/Quick/Nimble#using-nimble-without-xctest)?

- Jeff

**Comment by jeffh** [comment]
Closing, please try on [v3.0.0](https://github.com/Quick/Nimble/releases/tag/v3.0.0) and reopen issue if you're still having problems. Thanks!
