### ISSUE TITLE
No console output with Xcode 7.3

### ISSUE THREAD

**Issue by gapl** [Quick/Nimble#270]
After updating to Xcode 7.3 and the newest Nimble, I am not getting any console output for tests. 

Running the tests from within Xcode does appear to be running the tests (seen from the Test navigator), but the console output doesn't report any success or failure, or any mention of individual tests passing / failing.

I am linking the following issue from Quick ([#494](https://github.com/Quick/Quick/issues/494)), but wanted to open an issue here, as we are not using Quick ourselves so it looks like an isolated Nimble issue.

Fastlane's scan output:

```
+--------------------+-------+
|        Test Results        |
+--------------------+-------+
| Number of tests    | 0     |
| Number of failures | 0     |
+--------------------+-------+
```

**Comment by mendesbarreto** [comment]
Hello man!

I'm having the same issue here after I updated to xcode 7.3.

**Comment by jeffh** [comment]
Thanks for filling an issue.

Nimble doesn't do much with test reporting (only reporting assertion failures), so it's more likely a downstream issue to scan or whatever tooling you're using the parse tests from stdout since it seems like xctest no longer emits the output by default.

Closing for now.

**Comment by paweldudek** [comment]
@jeffh unfortunately looks like the issue actually lies within Nimble :cry: 

Specifically it looks like adding a custom tests observer (in this case `CurrentTestCaseTracker`) prevents default XCTest output from being printed onto console. Scan, and any other tool that relies on this output, will be broken since there's nothing to parse. 

I'm not yet entirely sure whether this is desired behaviour as there's little next to none documentation on this, but I'd rather say it's a bug in latest XCTest.

**Comment by phatblat** [comment]
I've logged this as [rdar://25456276](https://openradar.appspot.com/25456276)

**Comment by phatblat** [comment]
FYI, [rdar://25456276](http://www.openradar.me/25456276) is fixed in Xcode 8.
