### ISSUE TITLE
toRemain() or toEventuallyRemain() ?

### ISSUE THREAD

**Issue by ldiqual** [Quick/Nimble#281]
Hey there!

I'd like to make sure that a value remains the same for a whole time interval. Something like this:

```
var a = 0
expect { a }.toRemain(equal(0))
```

Is this something that can be accomplished with the current interface? If not, would it be worth adding?

Thanks!

**Comment by briancroom** [comment]
It seems to me that this kind of assertion should be used very rarely, if ever, because it would have such a negative effect on the speed of the test suite. That being said, you could do this to achieve something similar:

```swift
var a = 0
NSRunLoop.currentRunLoop().runUntilDate(NSDate(timeIntervalSinceNow: 1))
expect(a).to(equal(0))
```

This wouldn't poll the expression periodically, however I see relatively little value in doing that because it would only cut the time short when the test is failing, which is hopefully not a state you are in very often!

**Comment by ldiqual** [comment]
@briancroom Thanks a lot for your response! This is useful in view controller testing to ensure that pressing a button doesn't show a specific modal, for instance.

```
vc.button.sendActionsForControlEvents(.TouchUpInside)
expect { vc.presentedViewController }.toRemain(equal(nil))
```

I like your solution, and it'll mostly cover the case above even if not polling periodically. I understand that my case might be too specific for an inclusion in Nimble, so I'll just write my own extension here. Thanks!
