### ISSUE TITLE
How to verify closure not called

### ISSUE THREAD

**Issue by abbeycode** [Quick/Nimble#309]
I'm testing a method that doesn't always call its closure block. How can I use Nimble to verify it doesn't get called? This code is the closest I came, but when `waitUntil` times out, it fails the test.

``` Swift
var completionBlockCalled = false

waitUntil(timeout: 5.0) { done in
    myFunc {
        completionBlockCalled = true
        done()
    }
}

expect(completionBlockCalled) == false
```

**Comment by ashfurrow** [comment]
It's tricky to prove something is false – there are [entire wikipedia articles](https://en.wikipedia.org/wiki/Evidence_of_absence) on the subject, and unfortunately, this case is no exception. The code you will work, but will also add five seconds to every test run, which isn't great. I've looked through my code to find an example I could show you, but nothing strikes me as applicable to your case. I'd recommend considering a small restructure to your code: maybe the block is always called with a `success: Bool` parameter, or something similar. Good luck!

**Comment by briancroom** [comment]
👍 to @ashfurrow's comment. See also: https://github.com/Quick/Nimble/issues/281

**Comment by abbeycode** [comment]
@ashfurrow Good point.

@briancroom Thanks for that link. I liked your suggestion on that thread:

     NSRunLoop.currentRunLoop().runUntilDate(NSDate(timeIntervalSinceNow: 1))

**Comment by chunkyguy** [comment]
I also happened to run into a similar requirement today. Wouldn't it make sense to have a variant that takes a closure called on timeout, rather than internally calling `fail`? That sounds like a reasonable condition to test

I'm looking at this file https://github.com/Quick/Nimble/blob/master/Sources/Nimble/DSL+Wait.swift

```swift
case .timedOut:
                fail("Waited more than \(timeout.description)", file: file, line: line)
```

Every other case seems like to be originating from some sort of exception
