### ISSUE TITLE
Checking if value has a given type

### ISSUE THREAD

**Issue by SebastianOsinski** [Quick/Nimble#365]
Nimble has matchers `beAnInstanceOf` or `beKindOf`, which both expect tested value to be subclass of `NSObject` or Swift type bridged to ObjectiveC. Why there is no matcher which would work on pure Swift types? I.e. I have a method which returns some protocol and I would like to test if returned value has specific type.

I wrote such matcher myself and I think it would be valuable addition to built-in matchers, but such functionality seems very basic and I expected it to already exist, maybe there is something I missed which stopped you from implementing it?

**Comment by jeffh** [comment]
Historically, Swift prevented checking of types that were provable by the compiler - which meant all swift-only types. I'm pretty sure it's changed since then. But if it's possible to get pass and failure cases without the compiler giving you a warning then Nimble should have those matchers work with Swift types.

**Comment by jeffh** [comment]
This has been merged into master. Closing. Thanks for filing an issue @SebastianOsinski!
