### ISSUE TITLE
Make Nimble SwiftLint compatible

### ISSUE THREAD

**Issue by ltrainpr** [Quick/Nimble#370]
I asked a stackoverflow [question](http://stackoverflow.com/q/40643615/2226172) with more detail but figured I'd open an issue.  I'm attempting to add Quick and Nimble to an iOS wrapper app at work.  I'm getting all of these errors:

![image](https://cloud.githubusercontent.com/assets/3388706/20368946/9dd417ba-ac13-11e6-9b26-075088c5e8f0.png)

We are using Swift 3 and Swiftlint.  I was under the impression that Nimble 5.1.1 was compatible with Swift 3.  Any and all help is greatly appreciated.

---------------------------

Rules left:
  - [x] line_length
  - [x] todo
  - [x] ~~variable_name~~ identifier_name
  - [x] force_try
  - [x] function_parameter_count
  - [x] force_cast
  - [x] type_name

**Comment by ltrainpr** [comment]
From the answers in StackOverflow it seems that these are Swiftlint errors.  I'll have to figure out how to disable Swiftlint on 3rd party libraries so they don't fail the build.  

You should be aware that a lot of the Swift code in Nimble has issues.

**Comment by jeffh** [comment]
Hey @ltrainpr,

Thanks for filling an issue. We're aware that SwiftLint fails with Nimble, it's work schedule to be done, but it hasn't been completed yet. Related issue: https://github.com/Quick/Quick/issues/641. I'm going to change this issue to be Nimble's equivalent issue.

**Comment by sigito** [comment]
Hi guys,

I can do the initial setup of swiftlint. Do you have houndci attached to Nimble?
Do you have any specific set of rules in mind? Or would it be OK to just have SwiftLint with a default config (empty)?

**Comment by jeffh** [comment]
I've enabled HoundCI on Nimble. Thanks for the contribution @sigito!

**Comment by sigito** [comment]
There are still rules to enable left ([.swiftlint.yml](https://github.com/Quick/Nimble/blob/master/.swiftlint.yml). Should you have the same bug open as Quick/Quick#641, or reopen this one?

**Comment by jeffh** [comment]
Good point, I'll reopen this issue and update the body.

**Comment by lferro9000** [comment]
Hi,

I'm pushing a pull request to solve all of the outstanding issues.

One of them is done by a disable rule, because i don't know the finer details to make more drastic code changes on that area and because the matchers are going to be changed if i read the PR / WIP correctly, so having a temporary disable on there will not be too bad in the short time.

Naturally, it would be better to avoid it, so if someone with better understanding of the codebase can fix that one and remove the disable rule, that would be better imho.

Cheers,
LF
