### ISSUE TITLE
allPass and beNil can't work together

### ISSUE THREAD

**Issue by nandin-borjigin** [Quick/Nimble#388]
- [x] I have read [CONTRIBUTING](https://github.com/Quick/Nimble/blob/master/CONTRIBUTING.md) and have done my best to follow them.

### What did you do?

    let a: Double? = nil
    let b: Double? = nil
    expect([a, b]).to(allPass(beNil()))

### What did you expect to happen?

   The expectation should pass

### What actually happened instead?

   It fails instead

### Environment

 - Quick: Irrelevant
 - Nimble: 1.0 Nimble-iOS
 - Xcode Version: Version 8.2.1 (8C1002)
 - Swift Version: Xcode Default
 - Package manager : None, only using git submodule

### Project that demonstrates the issue

 Three line of code shown above will reproduce the issue

**Comment by sigito** [comment]
According to [AllPassTest](https://github.com/Quick/Nimble/blob/master/Tests/NimbleTests/Matchers/AllPassTest.swift#L99) WAI

**Comment by Nandiin** [comment]
Okay, then why? Expecting `[nil, nil, nil` to `allPass` a `beNil()` matcher is intuitive, isn't it?

**Comment by jeffh** [comment]
This is a bug. It was a limitation of an older implementation of Nimble that I think isn't a problem anymore.

**Comment by jeffh** [comment]
Hm, it's still a problem with the type hierarchy ATM. Perhaps a future release a Nimble will properly handle this situation.

**Comment by ikesyo** [comment]
This is still happening in 2018. Looks like the problem here is that the type evaluated in `beNil()` is `Double??` and the value is `Optional.some(.none)` so that value does not satisfy `beNil()` matcher.

- `beNil<T>() -> Predicate<T>` is evaluated as `beNil<Double?>() -> Predicate<Double?>`
- So `let actualValue = try actualExpression.evaluate()` is `Double??`
- `actualValue == nil` will be false because the `actualValue` is `Optional<Double?>.some(.none)` which is not nil
