### ISSUE TITLE
FatalError can't be tested in a function with returnvalue different to Void

### ISSUE THREAD

**Issue by olbrichj** [Quick/Nimble#415]
### What did you do?
expect { () -> Int in fatalError() }.to(raiseException())

### What did you expect to happen?
To pass

### What actually happened instead?
"Generic parameter T could not be inferred"

### Environment

 - Quick: *1.1.0*
 - Nimble: *6.0.1*
 - Xcode Version: *8.2.1*
 - Swift Version: *3.0* 
 - Carthage: *0.19.1*

**Comment by jeffh** [comment]
Hey @olbrichj,

Thanks for filing an issue. The following code you mentioned didn't work:

```swift
expect { () -> Int in fatalError() }.to(raiseException())
```

Is invalid because `fatalError()` doesn't return `Int`, but returns `Never`. Changing to:

```swift
expect { fatalError() }.to(raiseException())
```

Makes it compile. Although `fatalError()` doesn't raise an exception, but an assertion error (aka - it crashes the program). You'll want `throwAssertion()` instead.

If that doesn't work out, feel free to reopen this issue.
