### ISSUE TITLE
Use DispatchTimeInterval for interval configurations

### ISSUE THREAD

**Issue by ikesyo** [Quick/Nimble#694]

**Comment by ikesyo** [comment]
Closed by #718.

**Comment by NicholasTD07** [comment]
Long time user of the Quick and Nimble framework since Swift 1.0, I think. Really appreciate all the work you have been doing!

May I ask why this change happened? Without any description or context, it's hard to understand what's the benefit of this change. I have recently upgraded to Nimble, v9.0.0. I am pretty sure I am not the only one who got a lot of broken tests due to this change.

**Comment by ikesyo** [comment]
@NicholasTD07 Sorry for the inconvenience. I've just updated this issue's description.

**Comment by NicholasTD07** [comment]
@ikesyo Thanks! Yeah, it definitely help with type safety and also a clearer API.
