### ISSUE TITLE
postNotifications crashes or hangs up

### ISSUE THREAD

**Issue by iby** [Quick/Nimble#836]
- [x] I have read [CONTRIBUTING](https://github.com/Quick/Nimble/blob/master/CONTRIBUTING.md) and have done my best to follow them.

Migrated from 8.1.2 to 9.0.0 and the following code as well as other similar tests are failing with SIGSEGV or simply hang up for a minute or so and terminate.

```swift
expect({ compositionA.add(track) }).to(postNotifications(equal([
    Notification(name: Composition.tracksDidChangeNotification, object: compositionA),
    Notification(name: Composition.compositionDidChangeNotification, object: compositionA),
])))
```

It appears that the problem is with postNotifications `postNotifications` predicate itself. For example, it crashes with the most basic example, like:

```swift
expect({ compositionA.add(track) }).to(postNotifications(equal([])))
```

But works if I do: 

```swift
expect({ compositionA.add(track) }).toNot(throwError())
```

### Environment

- Quick: *2.2.1* (also tried with *3.0.0*)
- Nimble: *9.0.0*
- Xcode Version: *12.0.1 (12A7300)*
- Swift Version: *5.3 (swiftlang-1200.0.29.2 clang-1200.0.30.1)*
- Carthage: *0.36.0*

### Project that demonstrates the issue

Can't share any samples apart from the above but here's the stack in case it helps:

<img width="1552" alt="image" src="https://user-images.githubusercontent.com/1086845/95743788-58908180-0ca3-11eb-977e-5e9f5266980f.png">

**Comment by ianbytchek** [comment]
Digging deeper this seems to be not a problem directly with Nimble but with Swift itself doing some bridging or other Obj-C stuff when sending AVFoundation notifications. If I do the following I also get the crash in both 8.1.2 and 9.0.0:

```swift
let o = NotificationCenter.default.addObserver(forName: nil, object: nil, queue: nil, using: { _ in })
compositionA.add(track)
NotificationCenter.default.removeObserver(o)
```

However, Nimble 8.1.2 handles the same anonymous observing without crashing while 9.0.0 goes down. Any suggestions how to work around that?

**Comment by ianbytchek** [comment]
Narrowed down the cause and filed a [bug](https://bugs.swift.org/browse/SR-13729). This is not a problem with Nimble but it clearly used a way more failure proof approach in 8.x. Any chance the notification handling part can be reverted to earlier implementation?

**Comment by ikesyo** [comment]
> Narrowed down the cause and filed a bug.

Excellent! 👏 

> This is not a problem with Nimble but it clearly used a way more failure proof approach in 8.x. Any chance the notification handling part can be reverted to earlier implementation?

I'm really not sure what changes in Nimble v9 are related to this 🤔

**Comment by ianbytchek** [comment]
I did play around with it a little but not being familiar with the internals too well wanted to check with you first. I also didn't notice anything that stands out and tried plugging in the code from 8.x `PostNotification.swift` into the test suit directly and it fails like before. So, the problem is probably somewhere else, maybe with matchers.

Since the problem appears to be with bridging I tried using the selector observer with different parameter types. Erasing the type worked, but also did work using `NSNotification` rather than `Notification`. In this particular (AVFoundation) case the problems start when accessing the notification's object directly, which evidently happens during Swift bridging – if I'm not mistaken `__CFNotification` to `NSNotification` is handled by Obj-C runtime, so it's a different story. The following code works as expected:

```swift
import AVFoundation
import Foundation
import Nimble
import Quick

class Observer: NSObject {
    var notification: NSNotification?
    @objc func cb(n: NSNotification) { self.notification = n }
}

class Bug: Spec {
    override func spec() {
        fit("bug") {
            let observer = Observer()
            let notification = NSNotification(name: .init("foo"), object: NSObject())

            NotificationCenter.default.addObserver(observer, selector: #selector(Observer.cb), name: nil, object: nil)

            let asset = AVAsset(url: URL(fileURLWithPath: "~/Downloads/bbb.mov"))
            let _ = asset.tracks(withMediaType: .video).first
            expect(observer.notification).toNot(equal(notification))

            NotificationCenter.default.post(notification as Notification)
            expect(observer.notification).to(equal(notification))
        }
    }
}
```

Also tested against each individual notification (there are ~10 of them when the accessing the video track), they all work with the above:

```
name: assetNotice_PropertyLoaded user info: [AnyHashable("assetPayload_Property"): assetProperty_ResolvedURL]
name: assetNotice_PropertyFailedToLoad user info: [AnyHashable("assetPayload_Property"): assetProperty_ContentByteStream, AnyHashable("assetPayload_Result"): 2]
name: assetNotice_PropertyLoaded user info: [AnyHashable("assetPayload_Property"): assetProperty_ResolvedURL]
name: assetNotice_PropertyFailedToLoad user info: [AnyHashable("assetPayload_Property"): assetProperty_AssetType, AnyHashable("assetPayload_Result"): 2]
name: assetNotice_PropertyFailedToLoad user info: [AnyHashable("assetPayload_Result"): 2, AnyHashable("assetPayload_Property"): assetProperty_ContentByteStream]
name: assetNotice_PropertyFailedToLoad user info: [AnyHashable("assetPayload_Result"): 2, AnyHashable("assetPayload_Property"): availableMediaCharacteristicsWithMediaSelectionOptions]
name: assetNotice_PropertyFailedToLoad user info: [AnyHashable("assetPayload_Result"): 2, AnyHashable("assetPayload_Property"): assetProperty_AssetType]
name: assetNotice_PropertyFailedToLoad user info: [AnyHashable("assetPayload_Property"): assetProperty_Tracks, AnyHashable("assetPayload_Result"): 2]
name: assetNotice_PropertyFailedToLoad user info: [AnyHashable("assetPayload_Result"): 2, AnyHashable("assetPayload_Property"): availableMediaCharacteristicsWithMediaSelectionOptions]
name: assetNotice_PropertyFailedToLoad user info: [AnyHashable("assetPayload_Result"): 2, AnyHashable("assetPayload_Property"): assetProperty_Tracks]
```

Adapting this into existing `NotificationCollector` looks doable up to the point:

https://github.com/Quick/Nimble/blob/a5ed063448afd751f9bf477606c6477c1807fe2d/Sources/Nimble/Matchers/PostNotification.swift#L75

The generic predicate is for `Notification`, but collected notifications are `NSNotification`. Any ideas how to work around that considering `NSNotification` should not be casted to `Notification` to avoid accessing the associated object from Swift?

Alternatively, there's a similar approach that involves using the same observing but filtering out faulty notifications, i.e., `assetNotice_`-prefixed, (at least until Apple fixes the bridging) and casting them to `Notification`. I'm sure AVFoundation won't be the only place where this fails and this workaround will enable using the latest version Nimble.

What do you think?

**Comment by younata** [comment]
Hey @iby! Sorry about all this delay. I just want to confirm if this is still an issue with the current release (9.2.1) of Nimble?

**Comment by iby** [comment]
@younata Since Swift bugs are in the process of migration I can't check the bug status, but it seems the bridging is no longer failing. I just this with the old project and it seems to be working too. Let's close this down, I'll report if something ain't working in the future.
